name: Metrics

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate compact metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg

          user: MatheusSMA
          template: classic
          base: header, repositories
          config_timezone: America/Sao_Paulo

          # Só calendário e linguagens
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
